<?php

namespace App\DataFixtures;

use App\Entity\Joueur;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;
;

class JoueurFixtures extends Fixture implements DependentFixtureInterface
{
    public const JOUEURS = [
        // Orques Noirs
        [
            'nb_max' => 12,
            'poste' => 'Goblin bruiser lineman',
            'cout' => 45000,
            'comp_mvmt' => 6,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => 'Esquive, Poids plume, Minus, Crâne épais',
            'principale' => 'A',
            'secondaire' => 'GPF',
            'race' => 'Orques Noirs'
        ],
        [
            'nb_max' => 6,
            'poste' => 'Black Orcs',
            'cout' => 90000,
            'comp_mvmt' => 4,
            'comp_force' => 4,
            'comp_agilite' => '4+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Bagarreur, Projection',
            'principale' => 'GF',
            'secondaire' => 'AP',
            'race' => 'Orques Noirs'
        ],
        [
            'nb_max' => 1,
            'poste' => 'Trained Troll',
            'cout' => 150000,
            'comp_mvmt' => 4,
            'comp_force' => 5,
            'comp_agilite' => '5+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Toujours Affamé, Solitaire (3+), Gerbe de Vomi, Châtaigne (+1), Gros Débile, Régénération, Lancer de coéquipier',
            'principale' => 'F',
            'secondaire' => 'AGP',
            'race' => 'Orques Noirs'
        ],
        // Elus du chaos
        [
            'nb_max' => 16,
            'poste' => 'Beastman Runner Lineman',
            'cout' => 60000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '9+',
            'competences' => 'Cornes',
            'principale' => 'GMF',
            'secondaire' => 'AP',
            'race' => 'Elus du Chaos'
        ],
        [
            'nb_max' => 4,
            'poste' => 'Chosen Blocker',
            'cout' => 100000,
            'comp_mvmt' => 5,
            'comp_force' => 4,
            'comp_agilite' => '3+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => '',
            'principale' => 'GMF',
            'secondaire' => 'A',
            'race' => 'Elus du Chaos'
        ],
        [
            'nb_max' => 1,
            'poste' => 'Chaos Troll',
            'cout' => 115000,
            'comp_mvmt' => 4,
            'comp_force' => 5,
            'comp_agilite' => '5+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Toujours Affamé, Solitaire (4+), Gerbe de Vomi, Châtaigne (+1), Gros Débile, Régénération, Lancer de coéquipier',
            'principale' => 'MF',
            'secondaire' => 'AG',
            'race' => 'Elus du Chaos'
        ],
        [
            'nb_max' => 1,
            'poste' => 'Chaos Ogre',
            'cout' => 140000,
            'comp_mvmt' => 5,
            'comp_force' => 5,
            'comp_agilite' => '4+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Cerveau Lent, Crâne Epais, Solitaire (4+), Châtaigne (+1), Lancer de coéquipier',
            'principale' => 'MF',
            'secondaire' => 'AG',
            'race' => 'Elus du Chaos'
        ],
        [
            'nb_max' => 1,
            'poste' => 'Minautor',
            'cout' => 150000,
            'comp_mvmt' => 5,
            'comp_force' => 5,
            'comp_agilite' => '4+',
            'comp_passe' => '-',
            'comp_armure' => '9+',
            'competences' => 'Solitaire (4+), Frénésie, Cornes, Châtaigne (+1), Crâne Epais, Fureur Débridée',
            'principale' => 'MF',
            'secondaire' => 'AG',
            'race' => 'Elus du Chaos'
        ],
        // Renegats du chaos
        [
            'nb_max' => 12,
            'poste' => 'Renegade Human Lineman',
            'cout' => 50000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '9+',
            'competences' => '',
            'principale' => 'GM',
            'secondaire' => 'AF',
            'race' => 'Renégats du Chaos'
        ],
        [
            'nb_max' => 1,
            'poste' => 'Renegade Human Thrower',
            'cout' => 75000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '3+',
            'comp_armure' => '9+',
            'competences' => 'Animosité(tous coéquipiers), Passe, Libération Controlée',
            'principale' => 'GMP',
            'secondaire' => 'AF',
            'race' => 'Renégats du Chaos'
        ],
        [
            'nb_max' => 1,
            'poste' => 'Renegade Goblin',
            'cout' => 40000,
            'comp_mvmt' => 6,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => 'Animosité(tous coéquipiers), Esquive, Poids Plume, Minus',
            'principale' => 'AM',
            'secondaire' => 'GP',
            'race' => 'Renégats du Chaos'
        ],
        [
            'nb_max' => 1,
            'poste' => 'Renegade Orc',
            'cout' => 50000,
            'comp_mvmt' => 5,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Animosité(tous coéquipiers)',
            'principale' => 'GM',
            'secondaire' => 'AF',
            'race' => 'Renégats du Chaos'
        ],
        [
            'nb_max' => 1,
            'poste' => 'Renegade Skaven',
            'cout' => 50000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => 'Animosité(tous coéquipiers)',
            'principale' => 'GM',
            'secondaire' => 'AF',
            'race' => 'Renégats du Chaos'
        ],
        [
            'nb_max' => 1,
            'poste' => 'Renegade Dark Elf',
            'cout' => 75000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '2+',
            'comp_passe' => '3+',
            'comp_armure' => '9+',
            'competences' => 'Animosité(tous coéquipiers)',
            'principale' => 'AGM',
            'secondaire' => 'PF',
            'race' => 'Renégats du Chaos'
        ],
        [
            'nb_max' => 1,
            'poste' => 'Renegade Troll',
            'cout' => 115000,
            'comp_mvmt' => 4,
            'comp_force' => 5,
            'comp_agilite' => '5+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Châtaigne (+1), Gerbe de vomi, Gros Débile, Lancer de Coéquipier, Régénération, Solitaire (4+), Toujours Affamé',
            'principale' => 'F',
            'secondaire' => 'AGM',
            'race' => 'Renégats du Chaos'
        ],
        [
            'nb_max' => 1,
            'poste' => 'Renegade Ogre',
            'cout' => 140000,
            'comp_mvmt' => 5,
            'comp_force' => 5,
            'comp_agilite' => '4+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Cerveau Lent, Solitaire (4+), Châtaigne (+1), Crâne Epais, Lancer de Coéquipier',
            'principale' => 'F',
            'secondaire' => 'AGM',
            'race' => 'Renégats du Chaos'
        ],
        [
            'nb_max' => 1,
            'poste' => 'Renegade Minotaur',
            'cout' => 150000,
            'comp_mvmt' => 5,
            'comp_force' => 5,
            'comp_agilite' => '4+',
            'comp_passe' => '-',
            'comp_armure' => '9+',
            'competences' => 'Solitaire (4+), Frénésie, Cornes, Châtaigne (+1), Crâne Epais, Fureur Débridée',
            'principale' => 'F',
            'secondaire' => 'GAM',
            'race' => 'Renégats du Chaos'
        ],
        [
            'nb_max' => 1,
            'poste' => 'Renegade Rat Ogre',
            'cout' => 150000,
            'comp_mvmt' => 6,
            'comp_force' => 5,
            'comp_agilite' => '4+',
            'comp_passe' => '-',
            'comp_armure' => '9+',
            'competences' => 'Sauvagerie Animale, Frénésie, Solitaire (4+), Châtaigne (+1), Queue Préhensile',
            'principale' => 'F',
            'secondaire' => 'GAM',
            'race' => 'Renégats du Chaos'
        ],
        // Elfes Noirs
        [
            'nb_max' => 12,
            'poste' => 'Dark Elf Lineman',
            'cout' => 70000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '2+',
            'comp_passe' => '4+',
            'comp_armure' => '9+',
            'competences' => '',
            'principale' => 'AG',
            'secondaire' => 'F',
            'race' => 'Elfes Noirs',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Runners',
            'cout' => 80000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '2+',
            'comp_passe' => '3+',
            'comp_armure' => '8+',
            'competences' => 'Délestage',
            'principale' => 'AGP',
            'secondaire' => 'F',
            'race' => 'Elfes Noirs',
        ],
        [
            'nb_max' => 4,
            'poste' => 'Blitzers',
            'cout' => 100000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '2+',
            'comp_passe' => '4+',
            'comp_armure' => '9+',
            'competences' => 'Blocage',
            'principale' => 'AG',
            'secondaire' => 'PF',
            'race' => 'Elfes Noirs',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Assassins',
            'cout' => 85000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '2+',
            'comp_passe' => '5+',
            'comp_armure' => '8+',
            'competences' => 'Poursuite, Poignards',
            'principale' => 'AG',
            'secondaire' => 'PF',
            'race' => 'Elfes Noirs',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Witch Elves',
            'cout' => 110000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '2+',
            'comp_passe' => '5+',
            'comp_armure' => '8+',
            'competences' => 'Esquive, Frénésie, Rétablissement',
            'principale' => 'AG',
            'secondaire' => 'PF',
            'race' => 'Elfes Noirs',
        ],
        // Nains
        [
            'nb_max' => 12,
            'poste' => 'Dwarf Blocker Lineman',
            'cout' => 70000,
            'comp_mvmt' => 4,
            'comp_force' => 3,
            'comp_agilite' => '4+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Blocage, Tacle, Crâne Epais',
            'principale' => 'GF',
            'secondaire' => 'A',
            'race' => 'Nains',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Runners',
            'cout' => 85000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '9+',
            'competences' => 'Prise Sure, Crâne Epais',
            'principale' => 'GP',
            'secondaire' => 'AF',
            'race' => 'Nains',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Blitzers',
            'cout' => 80000,
            'comp_mvmt' => 5,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '10+',
            'competences' => 'Blocage, Crâne Epais',
            'principale' => 'GF',
            'secondaire' => 'AP',
            'race' => 'Nains',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Troll Slayer',
            'cout' => 95000,
            'comp_mvmt' => 5,
            'comp_force' => 3,
            'comp_agilite' => '4+',
            'comp_passe' => '-',
            'comp_armure' => '9+',
            'competences' => 'Blocage, Intrépidité, Frénésie, Crâne Epais',
            'principale' => 'GF',
            'secondaire' => 'A',
            'race' => 'Nains',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Deathroller',
            'cout' => 170000,
            'comp_mvmt' => 4,
            'comp_force' => 7,
            'comp_agilite' => '5+',
            'comp_passe' => '-',
            'comp_armure' => '11+',
            'competences' => 'Esquive en Force, Joeur Déloyal (+2), Juggernaut, Solitaire (5+), Châtaigne (+1), Sans les Mains, Arme Secrète, Stabilité',
            'principale' => 'F',
            'secondaire' => 'AG',
            'race' => 'Nains',
        ],
        // Union Elfique
        [
            'nb_max' => 12,
            'poste' => 'Linemen',
            'cout' => 60000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '2+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => '',
            'principale' => 'AG',
            'secondaire' => 'F',
            'race' => 'Union Elfique',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Throwers',
            'cout' => 75000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '2+',
            'comp_passe' => '2+',
            'comp_armure' => '8+',
            'competences' => 'Passe',
            'principale' => 'AGP',
            'secondaire' => 'F',
            'race' => 'Union Elfique',
        ],
        [
            'nb_max' => 4,
            'poste' => 'Catchers',
            'cout' => 100000,
            'comp_mvmt' => 8,
            'comp_force' => 3,
            'comp_agilite' => '2+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => "Réception, Nerfs d'Acier",
            'principale' => 'AG',
            'secondaire' => 'F',
            'race' => 'Union Elfique',
        ],
        [
            'nb_max' => 4,
            'poste' => 'Blitzers',
            'cout' => 115000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '2+',
            'comp_passe' => '3+',
            'comp_armure' => '9+',
            'competences' => 'Blocage, Glissade Controlée',
            'principale' => 'AG',
            'secondaire' => 'PF',
            'race' => 'Union Elfique',
        ],
        // Gobelins
        [
            'nb_max' => 16,
            'poste' => 'Goblin Lineman',
            'cout' => 40000,
            'comp_mvmt' => 6,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => 'Esquive, Poids Plume, Minus',
            'principale' => 'A',
            'secondaire' => 'GPF',
            'race' => 'Gobelins',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Bomma',
            'cout' => 45000,
            'comp_mvmt' => 6,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => 'Bombardier, Esquive, Arme Secrète, Minus',
            'principale' => 'A',
            'secondaire' => 'GPF',
            'race' => 'Gobelins',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Looney',
            'cout' => 40000,
            'comp_mvmt' => 6,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '-',
            'comp_armure' => '8+',
            'competences' => 'Tronçonneuse, Arme Secrète, Minus',
            'principale' => 'A',
            'secondaire' => 'GF',
            'race' => 'Gobelins',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Fanatic',
            'cout' => 70000,
            'comp_mvmt' => 3,
            'comp_force' => 7,
            'comp_agilite' => '3+',
            'comp_passe' => '-',
            'comp_armure' => '8+',
            'competences' => 'Chaîne et Boulet, Sans les Mains, Arme Secrète, Minus',
            'principale' => 'F',
            'secondaire' => 'AG',
            'race' => 'Gobelins',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Pogoer',
            'cout' => 75000,
            'comp_mvmt' => 7,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '5+',
            'comp_armure' => '8+',
            'competences' => 'Esquive, Echasse à Ressort, Minus',
            'principale' => 'A',
            'secondaire' => 'GPF',
            'race' => 'Gobelins',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Ooligan',
            'cout' => 65000,
            'comp_mvmt' => 6,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '6+',
            'comp_armure' => '8+',
            'competences' => 'Présence Perturbante, Esquive, Poids Plume, Minus',
            'principale' => 'A',
            'secondaire' => 'GPF',
            'race' => 'Gobelins',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Doom Diver',
            'cout' => 65000,
            'comp_mvmt' => 6,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '6+',
            'comp_armure' => '8+',
            'competences' => 'Poids Plume, Minus, Piqué',
            'principale' => 'A',
            'secondaire' => 'GF',
            'race' => 'Gobelins',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Trained Trolls',
            'cout' => 115000,
            'comp_mvmt' => 4,
            'comp_force' => 5,
            'comp_agilite' => '5+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Toujours Affamé, Gros Débile, Solitaire (3+), Châtaigne (+1), Lancer de Coéquipier, Gerbe de Vomi, Régénération',
            'principale' => 'F',
            'secondaire' => 'AGP',
            'race' => 'Gobelins',
        ],
        // Halflings
        [
            'nb_max' => 16,
            'poste' => 'Halfling Hopeful Lineman',
            'cout' => 30000,
            'comp_mvmt' => 5,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '7+',
            'competences' => 'Esquive, Poids Plume, Minus',
            'principale' => 'A',
            'secondaire' => 'GF',
            'race' =>'Halflings',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Halfling Heftys',
            'cout' => 50000,
            'comp_mvmt' => 5,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '3+',
            'comp_armure' => '8+',
            'competences' => 'Esquive, Parade, Minus',
            'principale' => 'AP',
            'secondaire' => 'GF',
            'race' => 'Halflings',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Halfling Catchers',
            'cout' => 55000,
            'comp_mvmt' => 5,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '3+',
            'comp_armure' => '8+',
            'competences' => 'Réception, Esquive, Poids Plume, Sprint, Minus',
            'principale' => 'A',
            'secondaire' => 'GF',
            'race' => 'Halflings',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Altern Forest Treemen',
            'cout' => 120000,
            'comp_mvmt' => 2,
            'comp_force' => 6,
            'comp_agilite' => '5+',
            'comp_passe' => '5+',
            'comp_armure' => '11+',
            'competences' => 'Châtaigne (+1), Stabilité, Bras Musclé, Prendre Racine, Crâne Epais, Lancer de Coéquipier, Timmm-ber',
            'principale' => 'AP',
            'secondaire' => 'GF',
            'race' => 'Halflings',
        ],
        // Humains
        [
            'nb_max' => 16,
            'poste' => 'Human Linemen',
            'cout' => 50000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '9+',
            'competences' => '',
            'principale' => 'G',
            'secondaire' => 'AF',
            'race' => 'Humain',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Throwers',
            'cout' => 80000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '2+',
            'comp_armure' => '9+',
            'competences' => 'Passe, Prise Sûre',
            'principale' => 'GP',
            'secondaire' => 'AF',
            'race' => 'Humain',
        ],
        [
            'nb_max' => 4,
            'poste' => 'Catchers',
            'cout' => 65000,
            'comp_mvmt' => 8,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '5+',
            'comp_armure' => '8+',
            'competences' => 'Réception, Esquive',
            'principale' => 'AG',
            'secondaire' => 'FP',
            'race' => 'Humain',
        ],
        [
            'nb_max' => 4,
            'poste' => 'Blitzers',
            'cout' => 85000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '9+',
            'competences' => 'Blocage',
            'principale' => 'GF',
            'secondaire' => 'AP',
            'race' => 'Humain',
        ],
        [
            'nb_max' => 3,
            'poste' => 'Halfling Hopeful',
            'cout' => 30000,
            'comp_mvmt' => 5,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '7+',
            'competences' => 'Esquive, Poids Plume, Minus',
            'principale' => 'A',
            'secondaire' => 'GF',
            'race' => 'Humain',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Ogre',
            'cout' => 140000,
            'comp_mvmt' => 5,
            'comp_force' => 5,
            'comp_agilite' => '4+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Cerveau Lent, Solitaire (4+), Châtaigne (+1), Lancer de Coéquipier, Crâne Epais',
            'principale' => 'F',
            'secondaire' => 'AG',
            'race' => 'Humain',
        ],
        // Noblesse Impériale
        [
            'nb_max' => 12,
            'poste' => 'Imperial Retainer Linemen',
            'cout' => 45000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '4+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => 'Parade',
            'principale' => 'G',
            'secondaire' => 'AF',
            'race' => 'Noblesse Impériale',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Imperial Throwers',
            'cout' => 75000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '3+',
            'comp_armure' => '9+',
            'competences' => 'Passe, Passe dans la Course',
            'principale' => 'GP',
            'secondaire' => 'AF',
            'race' => 'Noblesse Impériale',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Noble Blitzers',
            'cout' => 105000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '9+',
            'competences' => 'Blocage, Réception',
            'principale' => 'AG',
            'secondaire' => 'PF',
            'race' => 'Noblesse Impériale',
        ],
        [
            'nb_max' => 4,
            'poste' => 'Bodyguards',
            'cout' => 90000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '5+',
            'comp_armure' => '9+',
            'competences' => 'Stabilité, Lutte',
            'principale' => 'GF',
            'secondaire' => 'A',
            'race' => 'Noblesse Impériale',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Ogre',
            'cout' => 140000,
            'comp_mvmt' => 5,
            'comp_force' => 5,
            'comp_agilite' => '4+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Cerveau Lent, Solitaire (4+), Châtaigne (+1), Lancer de Coéquipier, Crâne Epais',
            'principale' => 'F',
            'secondaire' => 'AG',
            'race' => 'Noblesse Impériale',
        ],
        // Hommes-Lezards
        [
            'nb_max' => 12,
            'poste' => 'Skink Runner Linemen',
            'cout' => 60000,
            'comp_mvmt' => 8,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => 'Esquive, Minus',
            'principale' => 'A',
            'secondaire' => 'GPF',
            'race' => 'Hommes Lézards',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Chameleon Skink',
            'cout' => 70000,
            'comp_mvmt' => 7,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '3+',
            'comp_armure' => '8+',
            'competences' => 'Esquive, Sur le Ballon, Poursuite, Minus',
            'principale' => 'A',
            'secondaire' => 'GPF',
            'race' => 'Hommes Lézards',
        ],
        [
            'nb_max' => 6,
            'poste' => 'Saurus Blocker',
            'cout' => 85000,
            'comp_mvmt' => 6,
            'comp_force' => 4,
            'comp_agilite' => '5+',
            'comp_passe' => '6+',
            'comp_armure' => '10+',
            'competences' => '',
            'principale' => 'GF',
            'secondaire' => 'A',
            'race' => 'Hommes Lézards',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Kroxigor',
            'cout' => 140000,
            'comp_mvmt' => 6,
            'comp_force' => 5,
            'comp_agilite' => '5+',
            'comp_passe' => '-',
            'comp_armure' => '10+',
            'competences' => 'Cerveau Lent, Crâne Epais, Solitaire (4+), Châtaigne (+1), Queue Préhensile',
            'principale' => 'F',
            'secondaire' => 'AG',
            'race' => 'Hommes Lézards',
        ],
        // Horreus Nécromantiques
        [
            'nb_max' => 16,
            'poste' => 'Zombie Linemen',
            'cout' => 40000,
            'comp_mvmt' => 4,
            'comp_force' => 3,
            'comp_agilite' => '4+',
            'comp_passe' => '-',
            'comp_armure' => '9+',
            'competences' => 'Régénération',
            'principale' => 'G',
            'secondaire' => 'AF',
            'race' => 'Horreur Necromantiques',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Ghoul Runners',
            'cout' => 75000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => 'Esquive',
            'principale' => 'AG',
            'secondaire' => 'PF',
            'race' => 'Horreur Necromantiques',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Wraiths',
            'cout' => 95000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '-',
            'comp_armure' => '9+',
            'competences' => 'Blocage, Répulsion, Sans les Mains, Régénération, Glissade Controlée',
            'principale' => 'GF',
            'secondaire' => 'A',
            'race' => 'Horreur Necromantiques',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Werewolves',
            'cout' => 125000,
            'comp_mvmt' => 8,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '9+',
            'competences' => 'Griffes, Frénésie, Régénération',
            'principale' => 'AG',
            'secondaire' => 'PF',
            'race' => 'Horreur Necromantiques',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Flesh Golems',
            'cout' => 115000,
            'comp_mvmt' => 4,
            'comp_force' => 4,
            'comp_agilite' => '4+',
            'comp_passe' => '-',
            'comp_armure' => '10+',
            'competences' => 'Régénération, Stabilité, Crâne Epais',
            'principale' => 'GF',
            'secondaire' => 'A',
            'race' => 'Horreur Necromantiques',
        ],
        // Nurgle
        [
            'nb_max' => 12,
            'poste' => 'Rotter Linemen',
            'cout' => 35000,
            'comp_mvmt' => 5,
            'comp_force' => 3,
            'comp_agilite' => '4+',
            'comp_passe' => '6+',
            'comp_armure' => '9+',
            'competences' => 'Décomposition, Contagieux',
            'principale' => 'GM',
            'secondaire' => 'AF',
            'race' => 'Nurgle',
        ],
        [
            'nb_max' => 4,
            'poste' => 'Pestigors',
            'cout' => 75000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '9+',
            'competences' => 'Cornes, Contagieux, Régénération',
            'principale' => 'GMF',
            'secondaire' => 'AP',
            'race' => 'Nurgle',
        ],
        [
            'nb_max' => 4,
            'poste' => 'Bloaters',
            'cout' => 115000,
            'comp_mvmt' => 4,
            'comp_force' => 4,
            'comp_agilite' => '4+',
            'comp_passe' => '6+',
            'comp_armure' => '10+',
            'competences' => 'Présence Perturbante, Répulsion, Contagieux, Régénération',
            'principale' => 'GMF',
            'secondaire' => 'A',
            'race' => 'Nurgle',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Rotspawn',
            'cout' => 140000,
            'comp_mvmt' => 4,
            'comp_force' => 5,
            'comp_agilite' => '5+',
            'comp_passe' => '-',
            'comp_armure' => '10+',
            'competences' => 'Présence Perturbante, Répulsion, Solitaire (4+), Châtaigne (+1), Contagieux, Gros Débile, Régénération, Tentacules',
            'principale' => 'F',
            'secondaire' => 'AGM',
            'race' => 'Nurgle',
        ],
        // Ogres
        [
            'nb_max' => 16,
            'poste' => 'Gnoblar Linemen',
            'cout' => 15000,
            'comp_mvmt' => 5,
            'comp_force' => 1,
            'comp_agilite' => '3+',
            'comp_passe' => '5+',
            'comp_armure' => '6+',
            'competences' => 'Esquive, Poids Plume, Minus, Glissade Controlée, Microbe',
            'principale' => 'A',
            'secondaire' => 'G',
            'race' => 'Ogres',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Ogre Runt Punter',
            'cout' => 145000,
            'comp_mvmt' => 5,
            'comp_force' => 5,
            'comp_agilite' => '4+',
            'comp_passe' => '4+',
            'comp_armure' => '10+',
            'competences' => 'Cerveau Lent, Châtaigne (+1), Botter de coéquipier, Crâne Epais',
            'principale' => 'PF',
            'secondaire' => 'AG',
            'race' => 'Ogres',
        ],
        [
            'nb_max' => 5,
            'poste' => 'Ogre Blockers',
            'cout' => 140000,
            'comp_mvmt' => 5,
            'comp_force' => 5,
            'comp_agilite' => '4+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Cerveau Lent, Châtaigne (+1), Lancer de coéquipier, Crâne Epais',
            'principale' => 'F',
            'secondaire' => 'AGP',
            'race' => 'Ogres',
        ],
        // Alliance du vieux Monde
        [
            'nb_max' => 12,
            'poste' => 'Old World Human Linemen',
            'cout' => 50000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '9+',
            'competences' => '',
            'principale' => 'G',
            'secondaire' => 'AF',
            'race' => 'Alliance du Vieux Monde',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Old World Human Thrower',
            'cout' => 80000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '3+',
            'comp_armure' => '9+',
            'competences' => 'Animosité (tous coéquipier Dwarf ou Halfling), Passe, Prise Sûre',
            'principale' => 'GP',
            'secondaire' => 'AF',
            'race' => 'Alliance du Vieux Monde',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Old World Human Catcher',
            'cout' => 65000,
            'comp_mvmt' => 8,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '5+',
            'comp_armure' => '8+',
            'competences' => 'Animosité (tous coéquipier Dwarf ou Halfling), Réception, Esquive',
            'principale' => 'AG',
            'secondaire' => 'F',
            'race' => 'Alliance du Vieux Monde',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Old World Human Blitzer',
            'cout' => 90000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '9+',
            'competences' => 'Animosité (tous coéquipier Dwarf ou Halfling), Blocage',
            'principale' => 'GF',
            'secondaire' => 'A',
            'race' => 'Alliance du Vieux Monde',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Old World Dwarf Blockers',
            'cout' => 75000,
            'comp_mvmt' => 4,
            'comp_force' => 3,
            'comp_agilite' => '4+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Clé de Bras, Bagarreur, Solitaire (3+), Crâne Epais',
            'principale' => 'GF',
            'secondaire' => 'A',
            'race' => 'Alliance du Vieux Monde',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Old World Dwarf Runner',
            'cout' => 85000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '9+',
            'competences' => 'Solitaire (3+), Prise Sûre, Crâne Epais',
            'principale' => 'GP',
            'secondaire' => 'AF',
            'race' => 'Alliance du Vieux Monde',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Old World Dwarf Blitzer',
            'cout' => 80000,
            'comp_mvmt' => 5,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '10+',
            'competences' => 'Blocage, Solitaire (3+), Crâne Epais',
            'principale' => 'GF',
            'secondaire' => 'A',
            'race' => 'Alliance du Vieux Monde',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Old World Dwarf Troll Slayer',
            'cout' => 95000,
            'comp_mvmt' => 5,
            'comp_force' => 3,
            'comp_agilite' => '4+',
            'comp_passe' => '-',
            'comp_armure' => '9+',
            'competences' => 'Blocage, Intrépide, Frénésie, Solitaire (3+), Crâne Epais',
            'principale' => 'GF',
            'secondaire' => 'A',
            'race' => 'Alliance du Vieux Monde',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Old World Halfling Hopeful',
            'cout' => 30000,
            'comp_mvmt' => 5,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '7+',
            'competences' => 'Animosité (tous coéquipier Dwarf ou Humain), Minus, Esquive, Poids Plume',
            'principale' => 'GF',
            'secondaire' => 'A',
            'race' => 'Alliance du Vieux Monde',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Ogre',
            'cout' => 140000,
            'comp_mvmt' => 5,
            'comp_force' => 5,
            'comp_agilite' => '4+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Cerveau Lent, Solitaire (4+), Châtaigne (+1), Crâne Epais, Lancer de Coéquipier',
            'principale' => 'F',
            'secondaire' => 'AG',
            'race' => 'Alliance du Vieux Monde',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Altern Forest Treeman',
            'cout' => 120000,
            'comp_mvmt' => 2,
            'comp_force' => 6,
            'comp_agilite' => '5+',
            'comp_passe' => '5+',
            'comp_armure' => '11+',
            'competences' => 'Solitaire (4+), Prendre Racine, Châtaigne (+1), Stabilité, Bras Musclé, Crâne Epais, Lancer de Coéquipier, Timmm-ber',
            'principale' => 'F',
            'secondaire' => 'AGP',
            'race' => 'Alliance du Vieux Monde',
        ],
        // Orques
        [
            'nb_max' => 16,
            'poste' => 'Orc Lineman',
            'cout' => 50000,
            'comp_mvmt' => 5,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '10+',
            'competences' => 'Animosité (Orc Linemen)',
            'principale' => 'G',
            'secondaire' => 'AF',
            'race' => 'Orques',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Thrower',
            'cout' => 65000,
            'comp_mvmt' => 5,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '3+',
            'comp_armure' => '9+',
            'competences' => 'Animosité (Tous coéquipiers), Passe, Prise Sûre',
            'principale' => 'GP',
            'secondaire' => 'AF',
            'race' => 'Orques',
        ],
        [
            'nb_max' => 4,
            'poste' => 'Blitzers',
            'cout' => 80000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '10+',
            'competences' => 'Animosité (Tous coéquipiers), Blocage',
            'principale' => 'GF',
            'secondaire' => 'AP',
            'race' => 'Orques',
        ],
        [
            'nb_max' => 4,
            'poste' => 'Big Un Blockers',
            'cout' => 90000,
            'comp_mvmt' => 5,
            'comp_force' => 4,
            'comp_agilite' => '4+',
            'comp_passe' => '-',
            'comp_armure' => '10+',
            'competences' => 'Animosité (Big Un Blockers)',
            'principale' => 'GF',
            'secondaire' => 'A',
            'race' => 'Orques',
        ],
        [
            'nb_max' => 4,
            'poste' => 'Goblins',
            'cout' => 40000,
            'comp_mvmt' => 6,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => 'Esquive, Poids Plume, Minus',
            'principale' => 'A',
            'secondaire' => 'GF',
            'race' => 'Orques',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Untrained Troll',
            'cout' => 115000,
            'comp_mvmt' => 4,
            'comp_force' => 5,
            'comp_agilite' => '5+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Toujours Affamé, Gerbe de Vomi, Gros Débile, Lancer de Coéquipier, Solitaire (4+), Châtaigne (+1), Régénération',
            'principale' => 'F',
            'secondaire' => 'AGP',
            'race' => 'Orques',
        ],
        // Morts-Vivants
        [
            'nb_max' => 12,
            'poste' => 'Skeleton Linemen',
            'cout' => 40000,
            'comp_mvmt' => 5,
            'comp_force' => 3,
            'comp_agilite' => '4+',
            'comp_passe' => '6+',
            'comp_armure' => '8+',
            'competences' => 'Régénération, Crâne Epais',
            'principale' => 'G',
            'secondaire' => 'AF',
            'race' => 'Morts-Vivants',
        ],
        [
            'nb_max' => 12,
            'poste' => 'Zombie Linemen',
            'cout' => 40000,
            'comp_mvmt' => 4,
            'comp_force' => 3,
            'comp_agilite' => '4+',
            'comp_passe' => '-',
            'comp_armure' => '9+',
            'competences' => 'Régénération',
            'principale' => 'G',
            'secondaire' => 'AF',
            'race' => 'Morts-Vivants',
        ],
        [
            'nb_max' => 4,
            'poste' => 'Ghoul Runners',
            'cout' => 75000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => 'Esquive',
            'principale' => 'AG',
            'secondaire' => 'PF',
            'race' => 'Morts-Vivants',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Wight Blitzers',
            'cout' => 90000,
            'comp_mvmt' => 6,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '5+',
            'comp_armure' => '9+',
            'competences' => 'Blocage, Régénération',
            'principale' => 'GF',
            'secondaire' => 'AP',
            'race' => 'Morts-Vivants',
        ],
        [
            'nb_max' => 4,
            'poste' => 'Mummies',
            'cout' => 125000,
            'comp_mvmt' => 3,
            'comp_force' => 5,
            'comp_agilite' => '5+',
            'comp_passe' => '-',
            'comp_armure' => '10+',
            'competences' => 'Chataigne (+1), Régénération',
            'principale' => 'F',
            'secondaire' => 'AG',
            'race' => 'Morts-Vivants',
        ],
        // Snotlings
        [
            'nb_max' => 16,
            'poste' => 'Snotling linemen',
            'cout' => 15000,
            'comp_mvmt' => 5,
            'comp_force' => 1,
            'comp_agilite' => '3+',
            'comp_passe' => '5+',
            'comp_armure' => '6+',
            'competences' => 'Esquive, Poids Plume, Minus, Glissade Controlée, Microbe, Déferlement',
            'principale' => 'A',
            'secondaire' => 'G',
            'race' => 'Snotlings',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Fungus Flingas',
            'cout' => 30000,
            'comp_mvmt' => 5,
            'comp_force' => 1,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '6+',
            'competences' => 'Bombardier, Esquive, Poids Plume, Minus, Glissade Controlée, Arme Secrète',
            'principale' => 'AP',
            'secondaire' => 'G',
            'race' => 'Snotlings',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Fun-hoppas',
            'cout' => 20000,
            'comp_mvmt' => 6,
            'comp_force' => 1,
            'comp_agilite' => '3+',
            'comp_passe' => '5+',
            'comp_armure' => '6+',
            'competences' => 'Esquive, Poids Plume, Minus, Glissade Controlée, Echasse à Ressort',
            'principale' => 'A',
            'secondaire' => 'G',
            'race' => 'Snotlings',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Stilty Runnas',
            'cout' => 20000,
            'comp_mvmt' => 6,
            'comp_force' => 1,
            'comp_agilite' => '3+',
            'comp_passe' => '5+',
            'comp_armure' => '6+',
            'competences' => 'Esquive, Poids Plume, Minus, Glissade Controlée, Sprint',
            'principale' => 'A',
            'secondaire' => 'G',
            'race' => 'Snotlings',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Pump Wagon',
            'cout' => 105000,
            'comp_mvmt' => 4,
            'comp_force' => 5,
            'comp_agilite' => '5+',
            'comp_passe' => '-',
            'comp_armure' => '9+',
            'competences' => 'Joueur Déloyal (+1), Gros Débile, Juggernaut, Châtaigne (+1), Stabilité, Arme Secrète',
            'principale' => 'F',
            'secondaire' => 'AG',
            'race' => 'Snotlings',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Trained Trolls',
            'cout' => 115000,
            'comp_mvmt' => 4,
            'comp_force' => 5,
            'comp_agilite' => '5+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Toujours Affamé, Gros Débile, Solitaire (3+), Châtaigne (+1), Gerbe de Vomi, Régénération, Lancer de Coéquipier',
            'principale' => 'F',
            'secondaire' => 'AGP',
            'race' => 'Snotlings',
        ],
        // Skavens
        [
            'nb_max' => 16,
            'poste' => 'Skaven Clanrat Linemen',
            'cout' => 50000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => '',
            'principale' => 'G',
            'secondaire' => 'AMF',
            'race' => 'Skavens',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Throwers',
            'cout' => 85000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '2+',
            'comp_armure' => '8+',
            'competences' => 'Passe, Prise Sûre',
            'principale' => 'GP',
            'secondaire' => 'AMF',
            'race' => 'Skavens',
        ],
        [
            'nb_max' => 4,
            'poste' => 'Gutter Runners',
            'cout' => 85000,
            'comp_mvmt' => 9,
            'comp_force' => 2,
            'comp_agilite' => '2+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => 'Esquive',
            'principale' => 'AG',
            'secondaire' => 'MPF',
            'race' => 'Skavens',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Blitzers',
            'cout' => 90000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '5+',
            'comp_armure' => '9+',
            'competences' => 'Blocage',
            'principale' => 'GF',
            'secondaire' => 'AMP',
            'race' => 'Skavens',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Rat Ogre',
            'cout' => 150000,
            'comp_mvmt' => 6,
            'comp_force' => 5,
            'comp_agilite' => '4+',
            'comp_passe' => '-',
            'comp_armure' => '9+',
            'competences' => 'Sauvagerie Animale, Frénésie, Solitaire (4+), Châtaigne (+1), Queue Préhensile',
            'principale' => 'F',
            'secondaire' => 'AGM',
            'race' => 'Skavens',
        ],
        // Bas-Fonds
        [
            'nb_max' => 12,
            'poste' => 'Underworld Goblin Linemen',
            'cout' => 40000,
            'comp_mvmt' => 6,
            'comp_force' => 2,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => 'Esquive, Poids Plume, Minus',
            'principale' => 'AM',
            'secondaire' => 'GF',
            'race' => 'Bas-Fonds',
        ],
        [
            'nb_max' => 6,
            'poste' => 'Underworld Snotlings',
            'cout' => 15000,
            'comp_mvmt' => 5,
            'comp_force' => 1,
            'comp_agilite' => '3+',
            'comp_passe' => '5+',
            'comp_armure' => '6+',
            'competences' => 'Esquive, Poids Plume, Glissade Controlée, Minus, Déferlement, Microbe',
            'principale' => 'AM',
            'secondaire' => 'G',
            'race' => 'Bas-Fonds',
        ],
        [
            'nb_max' => 3,
            'poste' => 'Skaven Clanrat',
            'cout' => 50000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => 'Animosité (Underworld Goblin Linemen)',
            'principale' => 'GM',
            'secondaire' => 'AF',
            'race' => 'Bas-Fonds',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Skaven Thrower',
            'cout' => 85000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '2+',
            'comp_armure' => '8+',
            'competences' => 'Animosité (Underworld Goblin Linemen), Passe, Prise Sûre',
            'principale' => 'GMP',
            'secondaire' => 'AF',
            'race' => 'Bas-Fonds',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Gutter Runners',
            'cout' => 85000,
            'comp_mvmt' => 9,
            'comp_force' => 2,
            'comp_agilite' => '2+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => 'Animosité (Underworld Goblin Linemen), Esquive',
            'principale' => 'AGM',
            'secondaire' => 'PF',
            'race' => 'Bas-Fonds',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Skaven Blitzers',
            'cout' => 90000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '3+',
            'comp_passe' => '5+',
            'comp_armure' => '9+',
            'competences' => 'Animosité (Underworld Goblin Linemen), Blocage',
            'principale' => 'GMF',
            'secondaire' => 'AP',
            'race' => 'Bas-Fonds',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Underworld Troll',
            'cout' => 115000,
            'comp_mvmt' => 4,
            'comp_force' => 5,
            'comp_agilite' => '5+',
            'comp_passe' => '5+',
            'comp_armure' => '10+',
            'competences' => 'Toujours Affamé, Solitaire (4+), Châtaigne (+1), Gerbe de Vomi, Gros Débile, Régénération, Lancer de Coéquipier',
            'principale' => 'MF',
            'secondaire' => 'AGP',
            'race' => 'Bas-Fonds',
        ],
        [
            'nb_max' => 12,
            'poste' => 'Mutant Rat Ogre',
            'cout' => 115000,
            'comp_mvmt' => 6,
            'comp_force' => 5,
            'comp_agilite' => '4+',
            'comp_passe' => '-',
            'comp_armure' => '9+',
            'competences' => 'Sauvagerie Animale, Frénésie, Solitaire (4+), Châtaigne (+1), Queue Préhensile',
            'principale' => 'MF',
            'secondaire' => 'AG',
            'race' => 'Bas-Fonds',
        ],
        // Elfes Sylvains
        [
            'nb_max' => 12,
            'poste' => 'Wood Elf Linemen',
            'cout' => 70000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '2+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => '',
            'principale' => 'AG',
            'secondaire' => 'F',
            'race' => 'Elfes Sylvains',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Throwers',
            'cout' => 95000,
            'comp_mvmt' => 7,
            'comp_force' => 3,
            'comp_agilite' => '2+',
            'comp_passe' => '2+',
            'comp_armure' => '8+',
            'competences' => 'Passe',
            'principale' => 'AGP',
            'secondaire' => 'F',
            'race' => 'Elfes Sylvains',
        ],
        [
            'nb_max' => 4,
            'poste' => 'Catchers',
            'cout' => 90000,
            'comp_mvmt' => 8,
            'comp_force' => 2,
            'comp_agilite' => '2+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => 'Réception, Esquive',
            'principale' => 'AG',
            'secondaire' => 'PF',
            'race' => 'Elfes Sylvains',
        ],
        [
            'nb_max' => 2,
            'poste' => 'Wardancers',
            'cout' => 125000,
            'comp_mvmt' => 8,
            'comp_force' => 3,
            'comp_agilite' => '2+',
            'comp_passe' => '4+',
            'comp_armure' => '8+',
            'competences' => 'Blocage, Esquive, Saut',
            'principale' => 'AG',
            'secondaire' => 'PF',
            'race' => 'Elfes Sylvains',
        ],
        [
            'nb_max' => 1,
            'poste' => 'Loren Forest Treeman',
            'cout' => 120000,
            'comp_mvmt' => 2,
            'comp_force' => 6,
            'comp_agilite' => '5+',
            'comp_passe' => '5+',
            'comp_armure' => '11+',
            'competences' => 'Solitaire (4+), Prendre Racine, Châtaigne (+1), Stabilité, Bras Musclé, Crâne Epais, Lancer de Coéquipier',
            'principale' => 'F',
            'secondaire' => 'AG',
            'race' => 'Elfes Sylvains',
        ],
    ];
    public function load(ObjectManager $manager): void
    {
        foreach(self::JOUEURS as $data) {
            $joueur = new Joueur();
            $joueur->setNbMax($data['nb_max']);
            $joueur->setPoste($data['poste']);
            $joueur->setCout($data['cout']);
            $joueur->setCompMvmt($data['comp_mvmt']);
            $joueur->setCompForce($data['comp_force']);
            $joueur->setCompAgilite($data['comp_agilite']);
            $joueur->setCompPasse($data['comp_passe']);
            $joueur->setCompArmure($data['comp_armure']);
            $joueur->setComp($data['competences']);
            $joueur->setPrincipale($data['principale']);
            $joueur->setSecondaire($data['secondaire']);
            $joueur->setRaces($this->getReference('Race_' . $data['race']));
            $manager->persist($joueur);
        }

        $manager->flush();
    }

    public function getDependencies()
    {
        return [
            RaceFixtures::class,
        ];
    }
}
